name: llava
channels:
  - conda-forge
dependencies:
  - flash-attn
  - accelerate=0.29.3
  - av
  - deepspeed=0.14
  - cuda-compiler
  - hf-transfer
  - jmespath
  - mpi4py
  - open-clip-torch
  - transformers=4.40.0
  - wandb
  - torchvision
  - torchcodec
  - boto3
  - tyro
  - pynvml
  - py-spy
  - pip
  - pip:
      - decord
