image: ''
resProfiles: []
apt: []
paramGroups: []
gitRepo:
  branchName: ''
  mnt: ''
  repoName: ''
  commitSha: ''
  tag: ''
pip: []
imageMeta:
  imageVid: cn28egbc77u9j73q0pbg
  imageUrl: ''
  imageSid: ''
  taskId: 0
  imageSource: vid
  needBuild: false
pip3: []
params: []
env: {}
mlxCommandScript: ''
scms: []
engineScript: ''
inputs: []
entrypointMode: FULL_SCRIPT
outputs: []
defaultResProfileTitle: ''
subRepos: []
icmImage: ''
lazyDownloadCode: false
paramBinders: {}
resource:
  cpu: 1
  memory: 1024
  gpu: 0
  gpuType: NONE
  arnoldConfig:
    useTensorboard: false
    reminderInterval: 0
    roleImages: []
    hybrid: false
    retryTimes: 0
    clusterId: 24
    enableRayOnArnold: false
    queuePriority: 0
    resSchedulingPolicy: ''
    clusterSlice: ''
    buildRegion: ''
    profiler: ''
    keepMins: 0
    bytenasVolumes:
      - accessMode: RO
        name: vl-research-boli01-cn
        roles:
          - worker
    batchSize: 0
    multipleMachine: false
    assignHosts: []
    multiResourcePool: false
    ckptTrialId: 0
    quotaPool: default
    useTenantQuota: false
    tags: []
    clusterName: ''
    preemptible: false
    groupNames: []
    enableRay: false
    bytedriveVolumes: []
    batchServer: false
    maskHosts: []
    queueTimeoutReminder: 0
    roles:
      - resourcePool: ''
        numElastic: 0
        name: worker
        preemptible: false
        ports: 0
        num: 1
        memory: 327680
        gpu: 8
        disk: 0
        gpuv: A800_SXM_40GB
        cpu: 88
    gpuType: NONE
    groupIds:
      - 705
    protectHours: 0
    elasticTraining:
      openGangScheduler: false
      quotaPool: ''
      isOpen: false
    idc: ''
  backend: ARNOLD
name: vl_research_cn_boli01
codeRepoVersionNum: 0
pythonVersion: UNKNOWN
resProfileComments: ''
codeRepoName: ''
entrypointFullScript: pwd;
entryPoint: ''
arnoldTaskId: ''