resourcetype: arnold # 资源类型，平台限定为arnold，请勿更改
arnold:
    clusterid: 20 # arnold集群id，可以从arnold集群页面的网页链接中获取, https://arnold.byted.org/v2/cluster
    usergroupid: 1 # arnold用户组id, 可以从arnold用户组界面获取, https://arnold.byted.org/v2/group
    entrypoint: # 训练入口命令，例如python3 /path/to/your/python.py
    image:
        url: hub.byted.org/base/lab.pytorch2:4f035aea6ac458a0f71d88e0976de585 # 镜像url，可从MLX镜像中心或ICM上粘贴获取
        arnoldtaskid: null
    identity:
        psm: null # 是否使用某个特定psm作为鉴权身份，如果想保持个人身份请保留null
        psmidentityfirst: null
    roleconfig:
        # arnold worker配置, 为数组结构，平台默认生成首个worker配置，如果需要多机多卡训练，请自行添加修改
        - cpu: 4
          gpu: 1
          gpuv: # Tesla-V100-SXM2-32GB  A100-SXM-80GB A100-SXM4-40GB Tesla-T4, 任意GPU空字符串即可,建议从arnold用户组中复制, 否则如果用户组中不存在相应卡，则会一直排队
          mem: 16384
          num: 1
          numelastic: null
          ports: 1 # 需要预留端口数，后续预留端口从环境变量中获取
          role: worker
    gpuv: null # Tesla-V100-SXM2-32GB  A100-SXM-80GB A100-SXM4-40GB Tesla-T4, 任意GPU空字符串即可,建议从arnold用户组中复制, 否则如果用户组中不存在相应卡，则会一直排队
    env:
        ENV_EXAMPLE: THIS_IS_ENV1
    isdebug: null # 是否为debug模式
    keepmins: null # 训练失败后保留时间长度，默认15mins
    maskhosts: []
    # 是否将一些IP加入黑名单
    needreportfault: null
    preemptible: true # 是否可以被抢占
    hybrid: false # 是否为混部资源
    profiler: null # 启用 Arnold Profiler 分析训练任务。可能会对训练性能造成一点影响
    enablebatchserver: null # 是否开启batchserver, 不填为false, 使用文档: https://bytedance.feishu.cn/wiki/wikcnCMEhj73F7NpWUfDR06eweh
    enableray: null # 在 Arnold 获取的资源上创建 Ray 集群
    enabletensorboard: null # 为实例中启动TensorBoard服务指定专属端口，并生成相应的代理链接: 使用文档: https://site.bytedance.net/docs/4268/5820/69207/
    batchsize: null
    bytedrive: []
    # 复杂结构字段，建议在mlxlab前端repo 任务默认配置中配置完成后，再通过命令行生成
    bytenas: []
    # 复杂结构字段，建议在mlxlab前端repo 任务默认配置中配置完成后，再通过命令行生成
    packages: []
    scmrepo: []
    quotapool: null
